name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          check-latest: true
      - name: Verify Go version
        run: go version
      - name: Check formatting
        run: |
          gofmt -s -w $(git ls-files '*.go')
          git diff --exit-code
      - name: Run go vet
        run: go vet ./...
      - name: Run go build
        run: go build -v ./...
      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - name: Run gosec
        run: gosec -no-fail ./...
      - name: Run tests
        run: go test -v ./...
